# Generated by Django 2.1.4 on 2019-01-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_calchistory_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='calchistory',
            name='second_ID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
