# Generated by Django 2.1.4 on 2019-01-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_calchistory_second_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calchistory',
            name='second_ID',
        ),
    ]
