# Generated by Django 2.1.4 on 2019-01-27 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first', '0004_remove_calchistory_second_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrParsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField()),
                ('stroka0', models.CharField(max_length=255)),
                ('countWords', models.IntegerField()),
                ('countNumbers', models.IntegerField()),
                ('userWas', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
