# Generated by Django 2.1.4 on 2019-01-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_auto_20190127_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strparshistory',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='strparshistory',
            name='time',
            field=models.TimeField(),
        ),
    ]
