# Generated by Django 2.1.4 on 2019-01-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_auto_20190127_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strparshistory',
            name='time',
            field=models.CharField(max_length=8),
        ),
    ]
