# Generated by Django 2.1.4 on 2019-02-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_auto_20190127_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HP', models.IntegerField()),
                ('IQ', models.IntegerField()),
                ('Happiness', models.IntegerField()),
            ],
        ),
    ]
