# Generated by Django 2.1.4 on 2019-02-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentStat',
        ),
    ]
